---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels: { app.kubernetes.io/managed-by: platform-setup }
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels: { app.kubernetes.io/managed-by: platform-setup }
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels: { app.kubernetes.io/managed-by: platform-setup }
---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
  labels: { app.kubernetes.io/managed-by: platform-setup }
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels: { app.kubernetes.io/managed-by: platform-setup }
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels: { app.kubernetes.io/managed-by: platform-setup }
